### PR TITLE
Adding notebooks with module suggestion - open for discussion

### PR DESCRIPTION
**Pull request by malvikasharan**
# Summary

- Adding notebooks by modules (mostly empty) - please merge or remove as needed
  - content from module 3 will need to be sent to 4 and 5: @martinagvilas 
- Sarah's notebooks will be 6-7: @sgibson91 
- Have suggested 5-10 minutes video for each page - please remove as needed
- Suggesting data (chapters) discussed in #5

### CODE REVIEW

**Comment by malvikasharan** [comment]
This PR is better reviewed locally.

A quick overview of the notebooks created: 
image

Here is the module-wise description:
image

**Comment by martinagvilas** [comment]
Hey @malvikasharan I really like this idea! I could work on modules 3, 4 and 5 this morning.

Also, what were you planning for module 6? I think in this module we don't have any other option but to ask participants to do things locally right? If we are going to use github-pages to host the book instead of netflify, it might be worth splitting this module into two (similar to the official documentation): one where we show how participants can build locally and host their book online using `gh-pages`. And another one that shows you how to automate this process using GitHub actions. I started working on the first part yesterday, so I could add something to that.

**Comment by martinagvilas** [comment]
Also, I will merge this PR after moving all the contents from `book` to an outside folder as discussed in #3

**Comment by malvikasharan** [comment]
Thanks for the comment and cleaning up the data folder Martina. 

@sgibson91 what’s your opinion on module 6? 
I did have that in the notes taken with you both (with and without CI), but I totally missed that here. Feel free to add another module for that as needed.

**Comment by sgibson91** [comment]
> @sgibson91 what’s your opinion on module 6?

I think we only need to explain what binder/mybinder.org is. We can add a reference to one of my BinderHub talks/Zero-to-BinderHub workshop if people are interested in that.

I can try and play with adding a Binder notebook this afternoon

**Comment by martinagvilas** [comment]
@malvikasharan @sgibson91 Sorry I meant module 7, not 6 🤦‍♀️

**Comment by sgibson91** [comment]
> I think in this module we don't have any other option but to ask participants to do things locally right? 

Can we try adding a requirements.txt with jupyterbook to this repo, launching it on binder and then asking them to run the `jupyter-book build .` command in the terminal on binder?

**Comment by martinagvilas** [comment]
This is what we are doing in modules 3, 4 and 5 already. The issue comes when we want participants to create their own repository and build the book using github actions. Do you think we could also build this repo using binder?

**Comment by sgibson91** [comment]
If they're building with GitHub Actions, why do they need to build locally as well? Sorry, I'm confused. I haven't had a chance to read/review any of the material yet.

**Pull request merged**
