### PR TITLE
Update module 2 content and include objectives and takeaways in 2 and 3

### PR DESCRIPTION
**Pull request by malvikasharan**
# Summary

- Objectives and key takeaway are written using Carpentries format, like [this](https://swcarpentry.github.io/shell-novice/01-intro/index.html)
- Added content on Jupyter Book and The Turing Way
- Added a demo part

## Before merging this:

Review and merge #13 and rebase this branch to avoid merge conflict.

### CODE REVIEW

**Comment by malvikasharan** [comment]
@martinagvilas I have suggested some changes in module 3, but it doesn't overall changes anything in the flow that you have worked on.

1. Start even slower by building the book with only 2 markdown files
2. when we build Jupyter Book second time onward, I needed to delete the `_build` folders to update the structure in the book
3. `chapters:` doesn't display anything for me, I have used only `sections:` and nested them when creating a guide

Let me know what you think?

**Comment by martinagvilas** [comment]
Sorry @malvikasharan I read this just after the merge I did! 

> 1. Start even slower by building the book with only 2 markdown files

Agreed that this would be better! But I think I will post-pone this point until other more urgent things are finished to make sure we still got time for the video. Do you agree?

> 2. when we build Jupyter Book second time onward, I needed to delete the `_build` folders to update the structure in the book

I have updated the notebook to avoid these issues. Can you check again if this is still happening?

> 3\. `chapters:` doesn't display anything for me, I have used only `sections:` and nested them when creating a guide

That's weird! Are you using Jupyter Book 0.8.0? Is the version we are assuming in the tutorial and is in the `requirements.txt`

**Comment by malvikasharan** [comment]
Hey @martinagvilas. No worries about the merge, please double check if the 3rd module got any unintended edits that you would like to avoid (including the one with 'chapters' and 'sections' and deleting `_build` files)

**Comment by martinagvilas** [comment]
@malvikasharan cool! I'm looking at it now. There are a few commands that got lost but will incorporate them again with a new PR. I guess we should avoid working in the same notebooks at the same time because the merging is always horrible with them 😢

**Pull request merged**
