### PR TITLE
[WIP] Create intro notebook

### PR DESCRIPTION
**Pull request by martinagvilas**
This is a draft for the notebook that introduces jupyter-book. 

To-do:
- [x] Add basic commands to notebook
- [x] Add explanatory text to notebook
   - [x] Explain the content files
   - [x] Explain in more detail the `toc` file
   - [x] Explain in more detail the `config` file
- [x] Add jupyter-notebook example
- [x] Solve warnings in jupyter-book build
- [ ] Create warnings on purpose
- [ ] Solve warnings created on purpose
- [ ] Add answers to exercises

Maybe?
- [ ] change `ls` to use `tree`

### CODE REVIEW

**Comment by martinagvilas** [comment]
Hey @malvikasharan and @sgibson91! Can I get a review on this? 

It still has a few parts missing:
- We need to find a way to carry out the exercises part. I have added the basic outline, but they are not ready in terms of making sure the answer is correct and so on. There is a guideline [here](https://github.com/jupytercon/2020-malvikasharan/blob/master/Tutorial_Speakers_Guide.md) that we are suppose to follow, but I have never used that toolbox before. Have you?
- There is a part at the beginning where it would be nice to talk about The Turing Way. I though @malvikasharan might be interested in completing this part ❤️   so I left it empty for now
- I wanted to add a "common warnings" section at the end of the chapter, but I will do this after the review and if the second part of the tutorial gives me time

I will now start with the part of the tutorial that deals with creating your own github repo for jupyter-books in the meantime you look at this. But I will also ping you in that PR 😄

**Comment by malvikasharan** [comment]
Hey @martinagvilas. I am finishing my full day of meeting at 19:00 today and will take time to read this and review properly.

**Comment by sgibson91** [comment]
I plan on doing some tutorial stuff tomorrow afternoon and I'll make sure this is on my list 🙌

**Comment by martinagvilas** [comment]
Awesome! I'm tagging you in another PR so I don't forget to mention you any important details of what I'm doing, but answer my questions whenever its best for you 😄

**Comment by malvikasharan** [comment]
Excellent work @martinagvilas. An apology that it took me so long to actually get started with this. I took on too much and as the deadline moved, this kept moving too. However, now after reviewing this I feel motivated and back in the game.

A few comments on the current notebook: 

1. Do we need `content` folder inside `book`, or we should move all the files from content out to the `book` for simplicity?
2. In the step where you create the first to file, should that be only with the overview chapter to keep it minimal in the beginning? We can even remove the guide for reproducible research and start with only the overview chapter and slowly build that up by adding more chapters, or creating sections (like The Turing Way guide) in the book after demo-ing the first version of the minimal book.
3. In _The Turing Way_, we avoid numbering the chapter numbers as chapters in a book can be moved around as needed and numbering may cause naming issues in the future. 
However, if you think that numbering will make it easier for people to see what we are trying to show, that's ok to keep it too.
4. If everything works fine in the first round of build, the first exercise could be to add "Open" chapters 
  - here numbering can come in handy, but if we don't serialise them already, we can also ask them to organise chapters in a way that's most logical for them as there is no real chronology for the open science areas. 
5. the Second exercise could be what currently is the first exercise.
6. the book configuration can move to a new file - this can be paired with a 10 minutes explanation video.
7. Jupyter Notebooks part can be also moved to a separate file, paired with a 10 minutes video.

**Comment by martinagvilas** [comment]
Hey @malvikasharan, no worries and thanks for the feedback!

Replying to your comments:

- The reason why I created subfolders and enumerated the files is because I wanted to show the possibility of automatically building your `_toc.yml`, and for this we needed alphanumerical ordering. I didn't use this command in the end so we can remove it!

- I really like the idea of building the book more slowly. For doing this though, I would actually  completely move the `contents` folder outside the book, and in the tutorial ask participants to copy from the `contents` folder to the `book` folder the necessary files as needed. I would still create separate folders for each subchapter (I think in the Jupyter Book tutorial is shown that way).
     - Related: We still need to have the "cleaned" content files in this repo and not directly use the ones from The Turing Way to avoid the warnings. I was thinking that if we have time we could also pull some of the files from there directly to show common warnings and how to solve them.

- Also +1 in separating this into more subfolders (see my reply in #7)

**Comment by martinagvilas** [comment]
@malvikasharan I think its better if I close this PR and submit a new one separately for module 3, 4 and 5

**Pull request closed without merging**
